INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (1, 'user1', 'password1');
INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (2, 'user2', 'password2');

INSERT INTO TODOS(ID, DONE, TEXT, USER_ID) VALUES (1, false, 'sample todo 1', 1);
INSERT INTO TODOS(ID, DONE, TEXT, USER_ID) VALUES (2, false, 'sample todo 2', 1);
INSERT INTO TODOS(ID, DONE, TEXT, USER_ID) VALUES (3, false, 'sample todo 3', 1);
INSERT INTO TODOS(ID, DONE, TEXT, USER_ID) VALUES (4, false, 'sample todo 1', 2);
INSERT INTO TODOS(ID, DONE, TEXT, USER_ID) VALUES (5, false, 'sample todo 2', 2);
INSERT INTO TODOS(ID, DONE, TEXT, USER_ID) VALUES (6, false, 'sample todo 3', 2);

