CREATE TABLE USERS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
    );

CREATE TABLE TODOS (
      ID INTEGER NOT NULL AUTO_INCREMENT,
      DONE BOOLEAN DEFAULT FALSE,
      TEXT VARCHAR(255) NOT NULL,
      USER_ID INT,
      PRIMARY KEY (ID),
      FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    );

ALTER TABLE todos ALTER COLUMN id RESTART WITH 7; 
-- IMPORTANT since I insert 1 to 6 elements manually in data.sql